services:
  - type: web
    name: figma-clone-socket
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 